/*
 * Paganini's Caprice no. 5
 */

#define BEEP_NOTE_BASE 450
#include "beep.h"

#define NOTE_LENGTH 90

int main(void)
{
	int i;

	if(beep_init()) {
		fprintf(stderr, "Failed to init\n");
		return EXIT_FAILURE;
	}
	for(i = 0; i < 2; i++) {
		BEEP_PITCHED_NOTE(A, 3, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)

		BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)

		BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)
	}
	BEEP_PITCHED_NOTE(A, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C_SHARP, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C_SHARP, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(A, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(G, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(G, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 3, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(G_SHARP, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D_SHARP, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G_SHARP, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(G_SHARP, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 6, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 6, NOTE_LENGTH)

	for(i = 0; i < 2; i++) {
		BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)

		BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)

		BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(A, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
	}
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C_SHARP, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C_SHARP, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(A, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C_SHARP, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(F_SHARP, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(A, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 3, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(A_FLAT, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A_FLAT, 3, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(G, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(F_SHARP, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E_FLAT, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 6, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F_SHARP, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D_SHARP, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C_SHARP, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(F_SHARP, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E_FLAT, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(F_SHARP, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 6, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F_SHARP, 5, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C, 6, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 3, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(B, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 3, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 6, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B_FLAT, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A_FLAT, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F_SHARP, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E_FLAT, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D_FLAT, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(C, 5, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(B_FLAT, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A_FLAT, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F_SHARP, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E_FLAT, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(A, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)

	BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
	BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)

	for(int i = 0; i < 2; i++) {
		BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(E, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(G, 3, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(C, 4, NOTE_LENGTH)

		BEEP_PITCHED_NOTE(B, 3, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(G, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(F, 4, NOTE_LENGTH)
		BEEP_PITCHED_NOTE(D, 4, NOTE_LENGTH)
	}

	beep_end();
	return EXIT_SUCCESS;
}
